---
services:
  blackhole:
    image: charles474/blackhole:latest
    pull_policy: always
    container_name: blackhole
    labels:
      autoheal-app: true
    user: "1000:1000"
    volumes:
      - ${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}:${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}:${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}:/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}
      - ${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}:/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}
      - ./logs:/app/logs
      - ./healthcheck/blackhole:/healthcheck
      - /mnt:/mnt:rslave
      - /data:/data:rslave
    env_file:
      - .env
    environment:
      - BLACKHOLE_BASE_WATCH_PATH=/${BLACKHOLE_BASE_WATCH_PATH}
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    restart: unless-stopped
    healthcheck:
      test: /bin/bash "/healthcheck/healthcheck.sh"
      interval: 120s
      retries: 1
      start_period: 60s
      timeout: 15s

  blackhole_repair:
    image: charles474/blackhole:latest
    pull_policy: always
    container_name: blackhole_repair
    labels:
      autoheal-app: true
    user: "1000:1000"
    volumes:
      - ${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}:${REALDEBRID_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}:${TORBOX_MOUNT_TORRENTS_PATH:-/dev/null}
      - ${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}:/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_SONARR_PATH}
      - ${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}:/${BLACKHOLE_BASE_WATCH_PATH}/${BLACKHOLE_RADARR_PATH}
      - ./logs:/app/logs
      - ./healthcheck/blackhole:/healthcheck
      - /mnt:/mnt:rslave
      - /data:/data:rslave
    env_file:
      - .env
    environment:
      - BLACKHOLE_BASE_WATCH_PATH=/${BLACKHOLE_BASE_WATCH_PATH}
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    restart: unless-stopped
    command: python repair.py --mode symlink --include-unmonitored --no-confirm
    healthcheck:
      test: /bin/bash "/healthcheck/healthcheck.sh"
      interval: 120s
      retries: 1
      start_period: 60s
      timeout: 15s